<?php
/**
 * Created by PhpStorm.
 * User: weilone
 * Date: 2018/12/24
 * Time: 23:45
 */

namespace wechat\controllers;

use common\helpers\PayHelper;
use common\helpers\StringHelper;
use common\helpers\UrlHelper;
use common\models\bbb\MemberVipInfos;
use common\models\bbb\Orders;
use common\models\bbb\SmsLog;
use common\models\common\PayLog;
use common\models\member\MemberInfo;
use common\models\wechat\Fans;
use yii\helpers\Json;
use yii\web\Response;

class IndexController extends MyController
{

    function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    function actionIndex(){
        $vips = MemberVipInfos::findOne(['member_id'=>$this->memberId]);
        if ($vips){
            $time = time();
            $this->isVip = true;
            if ($time>$vips->vipstart_at && $time<$vips->vipend_at){
                $this->vipEnable = true;
            }
        }
        $data = [
            'isVip' => $this->isVip,
            'vipEnable' =>$this->vipEnable,
        ];
        return $this->render('index',$data);
    }

    function actionRegister(){
        if (\Yii::$app->request->isAjax){
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $vipMoney = \Yii::$app->request->post('vipMoney');
            $phone = \Yii::$app->request->post('phone');
            $phoneCode = \Yii::$app->request->post('phoneCode');
            $recommendCode = \Yii::$app->request->post('recommendCode');
            if ($vipMoney!=\Yii::$app->params['vipMoney']){
                return [
                    'msg'=>'金额错误，购买VIP需要￥'.\Yii::$app->params['vipMoney'],
                    'status'=>0
                ];
            }
            if (!$this->checkPhoneCode($phone,$phoneCode)){
                return [
                    'msg'=>'手机验证码有误',
                    'status'=>0
                ];
            }
            if (MemberInfo::findOne(['username'=>$phone])){
                return [
                    'msg'=>'抱歉，该手机号已被注册',
                    'status'=>0
                ];
            }else{
                $sn = 'BbB'.date('YmdHis').StringHelper::randomNum();
                $flag = \Yii::$app->db->transaction(function() use ($phone,$vipMoney,$recommendCode,$sn) {
                    $user = new MemberInfo();
                    $user->username = $phone;
                    $user->nickname = \Yii::$app->params['wechatMember']['nickname'];
                    $user->head_portrait = \Yii::$app->params['wechatMember']['avatar'];
                    $user->sex = \Yii::$app->params['wechatMember']['original']['sex'];
//                $user->area = \Yii::$app->params['wechatMember']['original']['country'];
                    $user->provinces = \Yii::$app->params['wechatMember']['original']['province'];
                    $user->city = \Yii::$app->params['wechatMember']['original']['city'];
                    $user->save();

                    $order = new Orders();
                    $order->order_sn = $sn;
                    $order->member_id = $user->id;
                    $order->money = $vipMoney;
                    $order->goods = '帮宝帮会员购买';
                    $order->desc = '帮宝帮会员购买';
                    $order->rec_code = $recommendCode;
                    $order->save();

                    \Yii::$app->session->set('user_info',$user->toArray());
                    Fans::updateAll(['member_id'=>$user->id],['openid'=>$this->openid]);

                    return true;
                });
                if ($flag){
                    return [
                        'status'=>1,
                        'msg'=>'下单成功',
                        'data'=>[
                            'order_sn' => $sn
                        ]
                    ];
                }
            }
            return [
                'msg'=>'抱歉，注册失败',
                'status'=>0
            ];
        }
        if ($this->memberId > 0){
            $this->redirect(['index/order-recharge']);
        }
        return $this->render('register');
    }


    function actionSearch(){

    }

    function actionOrderRecharge(){
        $orderInfo = Orders::find()->where(['member_id'=>$this->memberId])->orderBy(['id'=>SORT_DESC])->limit(1)->one();
        if ($orderInfo && $orderInfo->status==0){
            $data = $orderInfo->toArray();
        }else{
            $sn = 'BbB'.date('YmdHis').StringHelper::randomNum();
            $order = new Orders();
            $order->order_sn = $sn;
            $order->member_id = $this->memberId;
            $order->money = \Yii::$app->params['vipMoney'];
            $order->goods = '帮宝帮会员购买';
            $order->desc = '帮宝帮会员购买';
            $order->save();
            $data = $order->toArray();
        }
        $orderData = [
            'trade_type' => 'JSAPI', // JSAPI，NATIVE，APP...
            'body' => $data['goods'],
            'detail' => $data['desc'],
            'notify_url' => UrlHelper::toFront(['notify/wechat']), // 支付结果通知网址，如果不设置则会使用配置里的默认地址
            'out_trade_no' => PayHelper::getOutTradeNo($data['money']*100, $data['order_sn'], PayLog::PAY_TYPE_WECHAT), // 支付
            'total_fee' => $data['money']*100,
            'openid' => $this->openid, // trade_type=JSAPI，此参数必传，用户在商户appid下的唯一标识，
        ];

        $payment = \Yii::$app->wechat->payment;
        $result = $payment->order->unify($orderData);
        $json = '';
        if ($result['return_code'] == 'SUCCESS')
        {
            $json = $payment->jssdk->bridgeConfig($result['prepay_id']);
        }
        return $this->render('order-recharge',[
            'json'=>$json,
            'orderInfo'=>$data
        ]);

    }

    function actionOrderInfo(){
        $orderSn = \Yii::$app->request->get('orderSn');
        $orderInfo = Orders::findOne(['order_sn'=>$orderSn]);
        if (!$orderInfo){
            $this->redirect(UrlHelper::to(['site/error']));
        }
        $orderData = [
            'trade_type' => 'JSAPI', // JSAPI，NATIVE，APP...
            'body' => $orderInfo['goods'],
            'detail' => $orderInfo['desc'],
            'notify_url' => UrlHelper::toFront(['notify/wechat']), // 支付结果通知网址，如果不设置则会使用配置里的默认地址
            'out_trade_no' => PayHelper::getOutTradeNo($orderInfo['money']*100, $orderSn, PayLog::PAY_TYPE_WECHAT), // 支付
            'total_fee' => $orderInfo['money']*100,
            'openid' => $this->openid, // trade_type=JSAPI，此参数必传，用户在商户appid下的唯一标识，
        ];

        $payment = \Yii::$app->wechat->payment;
        $result = $payment->order->unify($orderData);
        $json = '';
        if ($result['return_code'] == 'SUCCESS')
        {
            $json = $payment->jssdk->bridgeConfig($result['prepay_id']);
        }
        return $this->render('order-info',[
            'json'=>$json,
            'orderInfo'=>$orderInfo->toArray()
        ]);
    }

    function actionSms(){
        if (\Yii::$app->request->isAjax && ($phone = \Yii::$app->request->get('phone'))){
            if (preg_match('/^1(3|4|5|8|7)[0-9]{9}$/',$phone)){
               //todo sms
                $sms = new SmsLog();
                if ($has = $sms::find()->where(['phone'=>$phone])->orderBy(['id'=>SORT_DESC])->one()){
                    if ((time() - $has['created_at'])<60*10){
                        exit(Json::encode([
                            'msg'=>'短信验证码获取时间不能超过10Min',
                            'status'=>0
                        ]));
                    }
                }
                if (YII_ENV!='prod'){
                    $code = 123456;
                }else{
                    $code = random_int(1000,999999);
                }
                $sms->phone = $phone;
                $sms->code = $code;
                if ($sms->save()){
                    exit(Json::encode([
                        'data'=>[
                            'code'=>$code
                        ],
                        'msg'=>'',
                        'status'=>1
                    ]));
                }
            }
        }
        exit(Json::encode([
            'data'=>[],
            'msg'=>'请输入正确的手机号',
            'status'=>0
        ]));
    }

    function checkPhoneCode($phone,$code){
        return SmsLog::find()->where(['phone'=>$phone,'code'=>$code])->orderBy(['id'=>SORT_DESC])->one();
    }
}