<?php
/**
 * Created by PhpStorm.
 * User: weilone
 * Date: 2019/1/6
 * Time: 16:58
 */

namespace wechat\controllers;


use yii\helpers\Url;

class NewController extends MyController
{

    function beforeAction($action)
    {
        if (!$this->vipEnable){
            return $this->redirect(Url::to(['index/index']))->send();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    function actionIndex(){

    }
}