<?php

namespace wechat\assets;

use common\helpers\ArrayHelper;
use yii\web\AssetBundle;

/**
 * Main wechat application asset bundle.
 */
class AppAsset extends AssetBundle
{
    public $basePath = '@bbb';

    public $baseUrl = '@bbb';

    public $css = [
        'css/weui.min.css',
        'css/jquery-weui.css',
        'font/iconfont.css',
        'css/common.css',
    ];

    public $js = [
        'font/iconfont.js',
        'js/jquery-2.1.4.js',
        'js/fastclick.js',
        'js/swiper.min.js',
        'js/common.js',
        'js/jquery-weui.js'
    ];

    public $depends = [
        // 'yii\web\YiiAsset',
        // 'yii\bootstrap\BootstrapAsset',
    ];

    public $jsOptions = ['position' => \yii\web\View::POS_HEAD];

    function init()
    {
        $css_arr = [
            'index'=>'css/index.css',
            'register'=>'css/register.css',
        ];
        if (isset($css_arr[\Yii::$app->controller->action->id])){
            $this->css = ArrayHelper::merge($this->css,[$css_arr[\Yii::$app->controller->action->id]]);
        }

        parent::init(); // TODO: Change the autogenerated stub
    }
}
